const API_PREFIX = "/api";
const APP_NAME = "Relax Zone";

const ROLES = {
  CLIENT: "CLIENT",
  ADMIN: "ADMIN",
};

const TOKEN_EXPIRATION = {
  ACCESS: "15m",
  REFRESH: "7d",
};

const BOOKING_MIN_LEAD_MINUTES = 60;
const BOOKING_CANCEL_MIN_LEAD_MINUTES = 60;

module.exports = { API_PREFIX, APP_NAME, ROLES, TOKEN_EXPIRATION, BOOKING_MIN_LEAD_MINUTES, BOOKING_CANCEL_MIN_LEAD_MINUTES };
